name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-test-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: make -e os=LINUX arch=AMD64
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install & Run PyTest
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/requirements.txt
        py.test -vv tests
      
  
      
